_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
                - 106
            "2":
                - 1
                - 55
                - 106
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
architecture:
    value: CNN
dataset:
    value: ERA
epochs:
    value: 20
learning_rate:
    value: 0.0001
