_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability diagram_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 54
                - 55
                - 106
            "2":
                - 1
                - 54
                - 55
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
                - 13
            "12": 0.19.6
            "13": linux-x86_64
        visualize:
            Reliability diagram:
                panel_config:
                    fieldSettings:
                        x: Truth
                        "y": Prediction
                    panelDefId: wandb/scatter/v0
                    stringSettings:
                        title: Reliability diagram
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Reliability diagram_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: ReLU
batch_size:
    value: 256
dropout:
    value: 0.5
groups:
    value: 1
hidden_layer_sizes:
    value:
        - 32
        - 64
input_variable:
    value:
        - u850
        - v850
kernel_sizes:
    value:
        - 3
learning_rate:
    value: 0.0001
num_classes:
    value: 1
num_epochs:
    value: 10
pool_sizes:
    value:
        - 2
region_predicted:
    value: 14
typee_prediction:
    value: regression
