_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 54
                - 55
                - 106
            "2":
                - 1
                - 54
                - 55
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
activation:
    value: ReLU
batch_size:
    value: 256
dropout:
    value: 0.5
groups:
    value: 1
hidden_layer_sizes:
    value:
        - 32
        - 64
input_variable:
    value:
        - z500
        - u850
kernel_sizes:
    value:
        - 3
learning_rate:
    value: 0.0001
num_classes:
    value: 10
num_epochs:
    value: 20
pool_sizes:
    value:
        - 2
region_predicted:
    value: 14
tpye_prediction:
    value: quantiles
