_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": train/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": val/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": test/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 54
                - 55
                - 106
            "2":
                - 1
                - 41
                - 54
                - 55
                - 106
            "3":
                - 7
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
                - 13
            "12": 0.19.6
            "13": linux-x86_64
