_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": reliability_diagram.vega.data.values._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.description
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.y.type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.x.field
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.x.type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.mark
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.layers
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.tooltip
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.data.values.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.y.title
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.$schema
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability_diagram_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Diagram_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.x.title
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": reliability_diagram.vega.encoding.y.field
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 54
                - 55
                - 106
            "2":
                - 1
                - 54
                - 55
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
                - 13
            "12": 0.19.6
            "13": linux-x86_64
        visualize:
            Reliability Diagram:
                panel_config:
                    fieldSettings: Truth
                    panelDefId:
                        encoding:
                            color:
                                field: Run Name
                                type: nominal
                            x:
                                field: Truth
                                type: quantitative
                            "y":
                                field: Prediction
                                type: quantitative
                        mark: line
                        title: Reliability Diagram (Multiple Runs)
                    stringSettings: Prediction
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Reliability Diagram_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Reliability_diagram:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: Truth
                        "y": Prediction
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Reliability diagram
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Reliability_diagram_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: ReLU
batch_size:
    value: 128
dropout:
    value: 0.5
groups:
    value: 1
hidden_layer_sizes:
    value:
        - 32
        - 64
input_variable:
    value:
        - z500
kernel_sizes:
    value:
        - 3
learning_rate:
    value: 0.001
num_classes:
    value: 1
num_epochs:
    value: 1
pool_sizes:
    value:
        - 2
region_predicted:
    value: 14
type_prediction:
    value: regression
