_wandb:
    value:
        cli_version: 0.19.6
        m:
            - "1": test/Histogram_test_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": test/Histogram_test_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/Histogram_test_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/Histogram_test_table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table.artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/Histogram_test_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/Histogram_test_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2.size
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/Histogram_test_table.ncols
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table.path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2.sha256
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/Histogram_test_table._latest_artifact_path
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Percentile Table._type
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Histogram_test_table.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": Reliability Table2.nrows
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 54
                - 55
                - 106
            "2":
                - 1
                - 54
                - 55
                - 106
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
                - 66
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
                - 13
            "12": 0.19.6
            "13": linux-x86_64
        visualize:
            Histogram_test:
                panel_config:
                    fieldSettings:
                        value: Prediction
                    panelDefId: wandb/histogram/v0
                    stringSettings:
                        title: Histogram
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Histogram_test_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            test/Histogram_test:
                panel_config:
                    fieldSettings:
                        value: Prediction
                    panelDefId: wandb/histogram/v0
                    stringSettings:
                        title: Histogram
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: test/Histogram_test_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: ReLU
batch_size:
    value: 128
dropout:
    value: 0.5
groups:
    value: 1
hidden_layer_sizes:
    value:
        - 32
        - 64
input_variable:
    value:
        - u850
kernel_sizes:
    value:
        - 3
learning_rate:
    value: 0.001
loss_fn:
    value: mse
num_classes:
    value: 1
num_epochs:
    value: 10
pool_sizes:
    value:
        - 2
region_predicted:
    value: 14
type_prediction:
    value: regression
