_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 55
                - 106
            "2":
                - 1
                - 41
                - 54
                - 55
                - 106
            "3":
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.3
            "5": 0.19.6
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
activation:
    value: ReLU
dropout:
    value: 0.5
hidden_layer_sizes:
    value:
        - 32
        - 64
input_variable:
    value:
        - z500
kernel_sizes:
    value:
        - 3
num_classes:
    value: 10
pool_sizes:
    value:
        - 2
